Dump child stderr in integration tests
Debugging this:

❯❯  rm -rf /tmp/mytmp/* ;TMPDIR=/tmp/mytmp/ LCI_TESTS_LEAK_TEMPDIRS=1 cargo stress
Compiling test binaries: cargo test --no-run --message-format=json
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.06s
Running test binary: "/home/brendan/src/local-ci/target/debug/local-ci"
Running test binary: "/home/brendan/src/local-ci/target/debug/deps/integration_test-cf54eb17f9fb893d"
Running test binary: "/home/brendan/src/local-ci/target/debug/deps/local_ci-837cbfdc19f9d6f2"
1 runs so far, 0 failures, over 0s
34 runs so far, 0 failures, over 5s
35 runs completed, 1 failures, over 5s

running 5 tests
test test_worktree_teardown::dirty_worktree ... ok
test test_worktree_teardown::clean_worktree ... ok
test test_worktree_teardown::really_dirty_worktree ... ok
test should_invalidate_cache_when_dep_changes ... ok
test shouldnt_leak_jobs ... FAILED

failures:

---- shouldnt_leak_jobs stdout ----
thread 'shouldnt_leak_jobs' panicked at tests/integration_test.rs:275:10:
worktree not found after 5s: timeout after 5s
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Panic happening, assuming its a test failure, dumping child stderr.
Error: Too many open files (os error 24)

failures:
    shouldnt_leak_jobs

test result: FAILED. 4 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 5.12s