debug: More verbose logging for Git output mysteries
I saw this:

Fatal error: setting revisions to test: Failed to parse result of GitCommand { _permit: SemaphorePermit { sem: Semaphore { ll_sem: Semaphore { permits: 0 } }, permits: 1 }, command: Command { std: cd "/home/brendan/src/linux" && "git" "-c" "color.ui=true " "log" "-n1" "--format=%H %T" "217e85f97031791fb48a2d374c7bdcf439365b21", kill_on_drop: false } } - ""

When I ran that same command it worked fine. What went wrong?
Something transient. Probably stderr said what it was.

(cherry picked from commit a0feb0e7bb61fd803766d7bf91284bbed834d0a4)